name: Train Chess AI

on:
  schedule:
    - cron: '*/15 * * * *'  # Exécuter toutes les 15 minutes

jobs:
  train-chess-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.0.1 chess

      - name: Run training script
        run: python train_ai.py

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add chess_ai.pth
          git commit -m "Update chess_ai.pth via training job"
          git push
