name: Train Chess AI

on:
  workflow_dispatch:  # Lancement manuel
  schedule:
    - cron: "0 * * * *"  # Lancer toutes les heures

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install torch==2.4.0  # Version compatible avec GitHub Actions

    - name: Train AI Model
      run: |
        python train.py
