name: Continuous Training of Chess AI

on:
  workflow_dispatch: # Lancement manuel du workflow

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.5.1 python-chess

      - name: Train AI
        run: |
          python train_ai.py
