name: Entraînement de l'IA Chess

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *'  # Lance l'entraînement toutes les 2 heures

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
    - name: Vérifier le dépôt
      uses: actions/checkout@v2

    - name: Configurer Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Installer les dépendances
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Exécuter le script d'entraînement
      run: |
        python train_ai.py
