name: Train and Upload Chess AI

on:
  schedule:
    - cron: '*/5 * * * *'  # Exécute toutes les 5 minutes
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  train-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérifier le code source
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python et installer les dépendances
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Étape 3 : Entraîner l'IA
      - name: Train Chess AI
        run: python train_ai.py

      # Étape 4 : Créer le fichier client_secrets.json
      - name: Create client_secrets.json
        run: |
          echo "${{ secrets.CLIENT_SECRET_JSON }}" > client_secrets.json

      # Étape 5 : Télécharger le fichier entraîné sur Google Drive
      - name: Upload model to Google Drive
        run: python upload_to_drive.py
