name: Train Chess AI

on:
  schedule:
    - cron: '*/1 * * * *'  # Exécuter toutes les 15 minutes

jobs:
  train-chess-ai:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set Git user
        run: |
          git config --global user.email "bernard.thomas2011@gmail.com"
          git config --global user.name "Thomasdelastreet"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install torch==2.0.1 chess

      - name: Run training script
        run: python train_ai.py

      - name: Push updated model to repository
        run: |
          git add chess_ai.pth --force
          git commit -m "Update model file after training" || echo "Nothing to commit"
          git push

