name: Train Chess AI

on:
  schedule:
    - cron: "*/13 * * * *" # Toutes les 5 minutes

jobs:
  train_ai:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Training Script
      run: python train_ai.py

    - name: Commit and Push Model
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        git add chess_ai.pth
        git commit -m "Update chess_ai.pth with new training data" || echo "No changes to commit"
        git push https://github-actions:${{ secrets.GH_PAT }}@github.com/Thomasdelastreet/Chessia.git main || echo "Push failed"


